spring:
  application:
    name: sharding-jdbc-demo
  profiles:
    include: sharding

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
